### ISSUE TITLE
Auto-Indent

### ISSUE THREAD

**Issue by orbisvicis** [t9md/vim-textmanip#4]
I'd like an option to re-indent code automatically during movement. I think this *only* makes sense in non-block (entire line) non-replace (move) mode. Perhaps something like:

```
" allow binding to force automatic re-indent
" Only available linewise, falls back to default behaviour blockwise
xmap <C-j> <Plug>(textmanip-move-down-indent)
xmap <C-k> <Plug>(textmanip-move-up-indent)

" toggle auto/manual indent for:
"    textmanip-move-down
"    textmanip-move-up
nmap <S-F10> <Plug>(textmanip-move-toggle-ident)
xmap <S-F10> <Plug>(textmanip-move-toggle-indent)
```

My jaw dropped when I found this plug-in. Vastly superior - should be more popular.

**Comment by t9md** [comment]
Your suggestion make sense for me, it is the feature I too considered before.
OK I recently didn't actively touching this plugin, so what I have to do is first to remember codebase of this plugin, its touch for me in this time.
Anyway, I will keep open this issue till I implement this feature one day.
Thanks,

**Comment by orbisvicis** [comment]
I understand. If I had time to go through a large unfamiliar code base, this issue would instead have been a pull request.

**Comment by t9md** [comment]
Now I can support auto-indent feature you suggested, after I tried auto-indent, I'm not sure its really helpful feature.
So I chose to provide as experimental `hook`.

See `https://github.com/t9md/vim-textmanip#experimental-hookhelper` if you are interested.
