### ISSUE TITLE
Normal Mode Moving

### ISSUE THREAD

**Issue by orbisvicis** [t9md/vim-textmanip#5]
Would it be possible to allow movement in normal mode? Defaults to entire line, without a visual selection? Something like:

```
" Applied to entire current line in normal mode
nmap <A-j> <Plug>(textmanip-move-down)
nmap <A-k> <Plug>(textmanip-move-up)
nmap <A-h> <Plug>(textmanip-move-left)
nmap <A-l> <Plug>(textmanip-move-right)
```

**Comment by t9md** [comment]
It was not possible, but I just pushed quick hack to latest, and you can now use only following two.
```vim
nmap <A-j> <Plug>(textmanip-move-down)
nmap <A-k> <Plug>(textmanip-move-up)
```

right and left need modification other parts, need refactoring,,, so its take time.

**Comment by t9md** [comment]
I rewrite/refactor almost all code, and you can now use normal mode movement.
Check out latest code.
